# STYLES
## ID HTML du conteneur
id:           ''
## Classe HTML du conteneur   
class:        ''
## Thème
theme:        'light'
## Texte du lien précédent
previous:     '&laquo;'
## Texte du lien suivant
next:         '&raquo;'
## Affichage des numéro de page
num:          true

# NUMEROTATION
##
range:        2
##
anchor:       3
##
gap:          1

# REQUETE DE RECUPERATION
## Classe de requête
query:        false
## Nombre d'élément par page
per_page:     0
## Numéro de la page courante
paged:        0

wp_enqueue_scripts: true